'use client';

/**
 * Analytics AI Insights Hero
 * ==========================
 * Premium header block that shows an executive summary of the analytics
 * generated by Claude Sonnet 4.5 (via /api/admin/analytics/ai-insights).
 *
 * States:
 *   - loading      → shimmer skeleton
 *   - success      → beautiful gradient card with headline, verdict pill,
 *                    highlights chips, recommendations list, forecast strip.
 *   - error/empty  → subtle fallback with "Refresh" CTA.
 */
import React, { useCallback, useEffect, useState } from 'react';
import {
  Sparkles, RefreshCw, TrendingUp, TrendingDown, Minus,
  Lightbulb, Radar, Zap, AlertTriangle, ChevronRight,
} from 'lucide-react';

type Verdict = 'positive' | 'neutral' | 'warning';

interface Insight {
  headline: string;
  verdict: Verdict;
  summary: string;
  highlights: Array<{ emoji: string; text: string }>;
  recommendations: Array<{ priority: 'high' | 'med' | 'low'; action: string; reason: string }>;
  forecast: string;
}

interface AiInsightsResponse {
  range: string;
  insights: Insight;
  context?: any;
  cached?: boolean;
  source?: string;
  model?: string;
  generated_at?: string;
  error?: string;
}

interface Props {
  range: string;
  token: string;
}

const VERDICT_STYLES: Record<Verdict, { bg: string; ring: string; iconBg: string; label: string; icon: React.ReactNode }> = {
  positive: {
    bg: 'from-emerald-500/25 via-emerald-500/10 to-transparent',
    ring: 'ring-emerald-500/30',
    iconBg: 'bg-emerald-500 text-white',
    label: 'CRECIMIENTO',
    icon: <TrendingUp className="w-3.5 h-3.5" />,
  },
  neutral: {
    bg: 'from-slate-500/15 via-slate-500/5 to-transparent',
    ring: 'ring-slate-500/20',
    iconBg: 'bg-slate-500 text-white',
    label: 'ESTABLE',
    icon: <Minus className="w-3.5 h-3.5" />,
  },
  warning: {
    bg: 'from-rose-500/25 via-rose-500/10 to-transparent',
    ring: 'ring-rose-500/30',
    iconBg: 'bg-rose-500 text-white',
    label: 'REVISAR',
    icon: <TrendingDown className="w-3.5 h-3.5" />,
  },
};

const PRIORITY_STYLES: Record<string, string> = {
  high: 'bg-rose-500/10 text-rose-600 border-rose-500/30',
  med:  'bg-amber-500/10 text-amber-600 border-amber-500/30',
  low:  'bg-slate-500/10 text-slate-600 border-slate-500/20',
};

export default function AnalyticsInsightsHero({ range, token }: Props) {
  const [data, setData] = useState<AiInsightsResponse | null>(null);
  const [loading, setLoading] = useState(true);
  const [refreshing, setRefreshing] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const fetchInsights = useCallback(async (refresh = false) => {
    if (refresh) setRefreshing(true); else setLoading(true);
    setError(null);
    try {
      const res = await fetch(
        `/api/admin/analytics/ai-insights?range=${encodeURIComponent(range)}${refresh ? '&refresh=1' : ''}`,
        { headers: { Authorization: `Bearer ${token}` } },
      );
      if (!res.ok) throw new Error(`${res.status}`);
      const json = await res.json();
      setData(json);
    } catch (e: any) {
      setError(e.message || 'error');
    } finally {
      setLoading(false);
      setRefreshing(false);
    }
  }, [range, token]);

  useEffect(() => { fetchInsights(false); }, [fetchInsights]);

  if (loading) {
    return (
      <div className="relative rounded-3xl p-5 lg:p-6 mb-6 bg-gradient-to-br from-indigo-500/10 via-fuchsia-500/5 to-transparent border border-white/[0.05] overflow-hidden">
        <div className="flex items-center gap-3 mb-4">
          <div className="w-10 h-10 rounded-xl bg-white/5 animate-pulse" />
          <div className="space-y-2 flex-1">
            <div className="h-3 w-24 bg-white/5 rounded animate-pulse" />
            <div className="h-5 w-2/3 bg-white/5 rounded animate-pulse" />
          </div>
        </div>
        <div className="space-y-2 mb-4">
          <div className="h-3 w-full bg-white/5 rounded animate-pulse" />
          <div className="h-3 w-5/6 bg-white/5 rounded animate-pulse" />
        </div>
        <div className="flex gap-2">
          {[0, 1, 2, 3].map(i => (
            <div key={i} className="h-8 w-24 bg-white/5 rounded-full animate-pulse" />
          ))}
        </div>
      </div>
    );
  }

  if (error || !data?.insights) {
    return (
      <div className="rounded-2xl p-4 mb-6 bg-white/[0.03] border border-white/[0.06] flex items-center gap-3">
        <AlertTriangle className="w-5 h-5 text-amber-400 shrink-0" />
        <div className="flex-1 min-w-0">
          <div className="text-sm font-bold text-slate-200">No pudimos generar los insights de IA</div>
          <div className="text-xs text-slate-500">Puede que la clave LLM no esté configurada o el servicio esté caído.</div>
        </div>
        <button
          onClick={() => fetchInsights(true)}
          className="text-xs px-3 py-1.5 rounded-lg bg-white/5 border border-white/10 text-slate-300 hover:bg-white/10"
        >Reintentar</button>
      </div>
    );
  }

  const ins = data.insights;
  const style = VERDICT_STYLES[ins.verdict] || VERDICT_STYLES.neutral;

  return (
    <div className={`relative rounded-3xl mb-6 ring-1 ${style.ring} overflow-hidden`}
         style={{ background: 'linear-gradient(135deg, rgba(15,23,42,0.6), rgba(15,23,42,0.9))' }}>
      {/* Ambient gradient */}
      <div className={`absolute inset-0 bg-gradient-to-br ${style.bg} pointer-events-none`} />
      {/* Sparkles pattern */}
      <div className="absolute -top-16 -right-16 w-64 h-64 rounded-full bg-gradient-to-br from-indigo-500/20 via-fuchsia-500/10 to-transparent blur-3xl pointer-events-none" />

      <div className="relative p-5 lg:p-6">
        {/* Header */}
        <div className="flex items-start justify-between gap-3 mb-3">
          <div className="flex items-center gap-3 min-w-0 flex-1">
            <div className="relative w-11 h-11 rounded-2xl bg-gradient-to-br from-indigo-500 via-violet-500 to-fuchsia-500 flex items-center justify-center shadow-lg shadow-violet-500/30 shrink-0">
              <Sparkles className="w-5 h-5 text-white" />
              <span className="absolute -top-1 -right-1 w-3 h-3 rounded-full bg-emerald-400 border-2 border-slate-900 animate-pulse" />
            </div>
            <div className="min-w-0 flex-1">
              <div className="flex items-center gap-1.5 mb-1">
                <span className="text-[10px] font-bold uppercase tracking-wider text-slate-400">
                  Rossy · IA
                </span>
                <span className={`inline-flex items-center gap-1 text-[9px] font-black px-1.5 py-0.5 rounded ${style.iconBg}`}>
                  {style.icon} {style.label}
                </span>
                {data.cached && (
                  <span className="text-[9px] font-bold px-1.5 py-0.5 rounded bg-slate-700 text-slate-300">CACHE</span>
                )}
              </div>
              <h2 className="text-base lg:text-lg font-black text-white leading-snug">
                {ins.headline}
              </h2>
            </div>
          </div>
          <button
            onClick={() => fetchInsights(true)}
            disabled={refreshing}
            title="Regenerar insights"
            className="shrink-0 p-2 rounded-lg bg-white/5 border border-white/10 text-slate-300 hover:bg-white/10 disabled:opacity-50"
          >
            <RefreshCw className={`w-3.5 h-3.5 ${refreshing ? 'animate-spin' : ''}`} />
          </button>
        </div>

        {/* Summary */}
        {ins.summary && (
          <p className="text-sm text-slate-300 leading-relaxed mb-4">{ins.summary}</p>
        )}

        {/* Highlights chips */}
        {Array.isArray(ins.highlights) && ins.highlights.length > 0 && (
          <div className="flex flex-wrap gap-1.5 mb-4">
            {ins.highlights.map((h, i) => (
              <div
                key={i}
                className="inline-flex items-center gap-1.5 bg-white/[0.04] backdrop-blur border border-white/[0.08] px-2.5 py-1.5 rounded-full text-[11px] text-slate-200"
              >
                <span className="text-sm">{h.emoji}</span>
                <span className="font-medium">{h.text}</span>
              </div>
            ))}
          </div>
        )}

        {/* Recommendations */}
        {Array.isArray(ins.recommendations) && ins.recommendations.length > 0 && (
          <div className="rounded-2xl bg-black/30 border border-white/[0.05] p-3 lg:p-4 mb-3">
            <div className="flex items-center gap-2 mb-2">
              <Lightbulb className="w-4 h-4 text-amber-400" />
              <span className="text-[11px] font-bold uppercase tracking-wider text-slate-400">Recomendaciones</span>
            </div>
            <div className="space-y-2">
              {ins.recommendations.slice(0, 4).map((r, i) => (
                <div key={i} className="flex items-start gap-2.5 group">
                  <span className={`text-[9px] font-black px-1.5 py-0.5 rounded uppercase border shrink-0 mt-0.5 ${PRIORITY_STYLES[r.priority] || PRIORITY_STYLES.low}`}>
                    {r.priority}
                  </span>
                  <div className="flex-1 min-w-0">
                    <div className="text-xs font-bold text-slate-100 leading-tight flex items-center gap-1">
                      <ChevronRight className="w-3 h-3 text-slate-500 group-hover:text-emerald-400 transition" />
                      {r.action}
                    </div>
                    {r.reason && (
                      <div className="text-[11px] text-slate-500 mt-0.5 pl-4">{r.reason}</div>
                    )}
                  </div>
                </div>
              ))}
            </div>
          </div>
        )}

        {/* Forecast strip */}
        {ins.forecast && (
          <div className="flex items-center gap-2 rounded-xl bg-gradient-to-r from-emerald-500/10 via-cyan-500/5 to-transparent border border-emerald-500/20 px-3 py-2">
            <Radar className="w-4 h-4 text-emerald-400 shrink-0" />
            <span className="text-[10px] font-bold uppercase tracking-wider text-emerald-400 shrink-0">Pronóstico</span>
            <span className="text-xs text-slate-200 leading-tight truncate">{ins.forecast}</span>
          </div>
        )}

        {/* Meta line */}
        <div className="mt-3 flex items-center justify-between text-[10px] text-slate-500">
          <span className="flex items-center gap-1">
            <Zap className="w-3 h-3" />
            {data.source === 'claude' ? 'Claude Sonnet 4.5' : data.source === 'fallback' ? 'Análisis local' : (data.model || '')}
          </span>
          {data.generated_at && (
            <span>
              Generado {new Date(data.generated_at).toLocaleString('es-MX', { hour: '2-digit', minute: '2-digit' })}
            </span>
          )}
        </div>
      </div>
    </div>
  );
}
